# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{omni_auth_myfc_id}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Tapaj\303\263s"]
  s.date = %q{2010-12-01}
  s.description = %q{description}
  s.email = ["marcos@tapajos.me"]
  s.homepage = %q{http://myfreecomm.com.br}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{summary}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oa-oauth>, ["= 0.1.6"])
    else
      s.add_dependency(%q<oa-oauth>, ["= 0.1.6"])
    end
  else
    s.add_dependency(%q<oa-oauth>, ["= 0.1.6"])
  end
end

